version: '3.1'

services:
  drupal:
      image: frupal:8.2
      ports:
        - "8080:80"
      volumes:
        - /var/www/html/modules
        - /var/www/html/profiles
        - /var/www/html/themes
        - /var/www/html/sites
  postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD_FILE=/run/secrets/psql-pw
      secrets:
        - psql-pw
      volumes:
        - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data:

secrets:
  psql-pw:
    external: true

#echo "<string>" | docker secret psql-pw - <value>