version: '3'

services:
  proxy:
    image: nginx:1.13 # this will use the latest version of 1.13.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro #Bind mount to a file called ngnix.conf. Taking a file from my local env to the container. ro means read only in the container
  web:
    image: httpd  # this will use httpd:latest
