version: '2'

# based off compose-sample-2, only we build nginx.conf into image
# uses sample site from https://startbootstrap.com/template-overviews/agency/

services:
  proxy:
    build:
      context: . #Current directory
      dockerfile: nginx.Dockerfile
    image: ngnix-custom #name it with a custom name to get it stored in local cache. When we run docker-compose up its going to check if its in the cache
    ports:
      - '80:80'
  web:
    image: httpd
    volumes:
      - ./html:/usr/local/apache2/htdocs/